config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
  }

  devise_scope :user do
    get  'users/index' => 'users/registrations#index'
    post 'sign_up' => 'users/registrations#new'
    post 'users/logout'  => 'users/sessions#logout'
  end

  root 'items#index'
  get "users/in_progress" => "users#in_progress"
  get "users/completed" => "users#completed"
  get "users/purchase" => "users#purchase"
  get "users/purchased" => "users#purchased"
  get "users/listing" => "users#listing"
  get "users/logout" => "users#logout"
  resources :users, only: [:index, :edit, :update, :show] do
      resources :user_details, only: [:new , :create, :edit, :update]
  end
  get "items/area/:prefecture" => "items#area"
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    post :payjp, on: :member
    get :buy, on: :member
    get :stop, on: :member
    get :resume, on: :member
  end
  post "items/create" => "items/create"
  resources :category, only: [:index,:show]

  resources :blands, only: [:index]

  resources :large_category, only: [:show, :index] do
    resources :medium_category, only: [:show] do
      resources :small_category, only: [:show]
    end
  end

  # get "large_category/:large_category_id" => "category#large_category"
  # get "category/medium_category/:large_category_id/:medium_category_id" => "category#medium_category"
  # get "category/small_category/:large_category_id/:medium_category_id/:small_category_id" => "category#small_category"

  resources :transaction_details, only: [:show, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one  :user_detail, dependent: :destroy
  accepts_nested_attributes_for :user_detail, update_only: true
  has_many :items, dependent: :destroy
  has_many :bought_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :saling_items, ->{where("buyer_id is NULL")}, foreign_key: "saler_id", class_name: "Item"
  has_many :sold_items, ->{where("buyer_id is not NULL")}, foreign_key: "saler_id", class_name: "Item"
  has_many :likes, dependent: :destroy
  has_many :evaluations
  has_many :todos, dependent: :destroy
  has_many :points, dependent: :destroy

  validates :nickname, presence: true, length: { maximum:10 }
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_account_update_params, only: [:update]


  def index
  end

  # GET /resource
  def new
    super
  end

  def create
    @user = User.new(sign_up_params)
      if verify_recaptcha
        super
      else
          respond_with_navigational(resource) {render :new}
      end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
     new_user_user_detail_path(resource)
  #   super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user ,only:[:index,:in_progress,:completed,:purchase,:purchased,:listing, :logout]
  # before_action :set_current_user, only: [:create,:edit,:update]
  before_action :create_user_detail ,only:[:edit]

  def index
    @item = Item.where(user_id: current_user.id)
    @items = Item.be_bought(@user.id).where.not(status: 2).order("created_at DESC")
    @bought_items = Item.be_bought(@user.id).where(status: 2).order("created_at DESC")
  end

  def show
    @user = User.find(params[:id])
    @userdetail = @user.user_detail
    # @user.user_detail = UserDetail.new if @user.user_detail.blank?
    # @userdetail = UserDetail.find_by(params[:user_id])
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to root_path, notice: "権限がありません"
    # @userdetail = UserDetail.find_by(params[:user_id])
    # if current_user.id == @userdetail.user_id
    else
      # @user = User.find(params[:id])
      @user.user_detail = UserDetail.new if @user.user_detail.blank?
      @userdetail = UserDetail.find_by(params[:user_id])
    end
    # else
    #   redirect_to new_user_user_detail_path
    # end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path
  end

  def in_progress
    @items = @user.items.be_sold.where.not(status: :received).order("created_at DESC")
  end

  def completed
    @items = @user.items.be_sold.where(status: :received).order("created_at DESC")
  end

  def purchase
    @items = Item.be_bought(@user.id).where.not(status: :received).order("created_at DESC")
  end

  def purchased
    @items = Item.be_bought(@user.id).where(status: :received).order("created_at DESC")
  end

  def listing
    @items = @user.items.where(status: :stopped).order("created_at DESC") .or @user.items.where(status: :displayed).order("created_at DESC")
  end

  def logout
  end

  private

  def user_params
    params.require(:user).permit(:nickname ,:id, user_detail_attributes:[:profile])
  end

  def userdetail_params
    params.require(:user_detail).permit(:profile).merge(user_id: current_user.id)
  end

  def set_profile
    @userdetail = UserDetail.find(params[ :profile]).merge(user_id: current_user.id)
  end

  def set_user
    @user = User.find_by(id: current_user.id)
  end

  def create_user_detail
    @user = User.find(current_user.id)
    @userdetail = @user.user_detail
    if @userdetail.nil?
      redirect_to new_user_user_detail_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_buying_item.html.haml
%section.mypage-tab-container
  %h2.mypage-tab-head.bold 購入した商品
  %ul.listing-tabs
    %li.half-tab.tab-label.active
      %h3.bold 取引中
    %li.half-tab.tab-label
      %h3.bold  購入済
  .history-container__content
    - if items.length != 0
      %ul.mypage-item-list.active
        - items.each do |item|
          %li
            .mypage-item-link
              = link_to transaction_detail_path(item.id) do
                %figure
                  = image_tag item.images.first.image, width: "48", height: "48", class: "clearfix"
                .mypage-item-body
                  .mypage-item-text
                    = item.item_name
                  .mypage-item-box.font-2
                    %i{class: "far fa-heart heart-icon"}
                    %span 10
                    .btn-blue.sell-btn 配送待ち
                    %i.fas.fa-angle-right.fa-lg
                    = fa_icon("fa-angle-right")
    - else
      %ul.history-container__content
        %li.mypage-item-not-found.bold.mypage-item-list.active
          取引中の商品がありません
    - if bought_items.length != 0
      %ul.mypage-item-list
        - bought_items.each do |item|
          %li
            .mypage-item-link
              = link_to transaction_detail_path(item.id) do
                %figure
                  = image_tag item.images.first.image, width: "48", height: "48", class: "clearfix"
                .mypage-item-body
                  .mypage-item-text
                    = item.item_name
                  .mypage-item-box.font-2
                    %i{class: "far fa-heart heart-icon"}
                    %span 10
                    .btn-blue.sell-btn 購入完了
                    = fa_icon("fa-angle-right")
    - else
      %ul.history-container__content
        %li.mypage-item-not-found.bold.mypage-item-list
          購入済の商品がありません

app/views/users/_buying_list.html.haml
%main.l-container
  %section.mypage-tab-container
    %h2.mypage-tab-head.bold 取引中の商品
    %ul.listing-tabs
      %li
        %h3  出品中
        %a
      - if action_name == "purchase"
        %li.active
          %h3  取引中
      -else
        %li
          %h3  取引中
      - if action_name == "purchased"
        %li.active
          %h3  購入済
      -else
        %li
          %h3  購入済
    .tab-content
      - if @items.length != 0
        %ul.notification__content
          - @items.each do |item|
            %li
              .mypage-item-link
                - if action_name == "purchase"
                  =link_to transaction_detail_path(item.id) do
                    %figure
                      = image_tag item.images.first.image, width: "48"
                    .mypage-item-body
                      .mypage-item-text
                        %ul
                          %li
                            = item.item_name
                          %li
                            取引中
                - if action_name == "purchased"
                  %figure
                    = image_tag item.images.first.image, width: "48"
                  .mypage-item-body
                    .mypage-item-text
                      %ul
                        %li
                          = item.item_name
                        %li
                          購入済み
      - else
        %ul.mypage-item-list
        %li.mypage-item-not-found.bold
          - if action_name == "purchase"
            取引中の商品がありません
          - if action_name == "purchased"
            購入済みの商品がありません
  %ul.mypage-history
    %li.paper-prev.paper-cell
    %li.paper-nextpaper-cell

app/views/users/_footer_sell_btn.html.haml
= link_to(new_item_path,class:"footer-sell-btn") do
  .footer-sell-btn__content
    .footer-sell-btn__content--text
      出品
    %i.fas.fa-camera.fontsize

app/views/users/_selling_list.html.haml
%main.l-container
  %section.mypage-tab-container
    %h2.mypage-tab-head.bold 取引中の商品
    %ul.listing-tabs
      %li
        %h3  出品中
        %a
      - if action_name == "in_progress"
        %li.active
          %h3  取引中
      - else
        %li
          %h3  取引中
      - if action_name == "completed"
        %li.active
          %h3  売却済
      - else
        %li
          %h3  売却済
    .tab-content
      - if items.length != 0
        %ul.notification__content
          - items.each do |item|
            %li
              .mypage-item-link
                - if action_name == "in_progress"
                  = link_to  transaction_detail_path(item.id) do
                    %figure
                      = image_tag item.images.first.image, width: "48"
                    .mypage-item-body
                      .mypage-item-text
                        %ul
                          %li
                            = item.item_name
                          %li
                            取引中
                - if action_name == "completed"
                  %figure
                    = image_tag item.images.first.image, width: "48"
                    .mypage-item-body
                      .mypage-item-text
                        %ul
                          %li
                            = item.item_name
                            %li
                              販売済み
      - else
        %ul.mypage-item-list
        %li.mypage-item-not-found.bold
          - if action_name == "in_progress"
            取引中の商品がありません
          - if action_name == "completed"
            売却済みの商品がありません
  %ul.mypage-history
    %li.paper-prev.paper-cell
    %li.paper-nextpaper-cell

app/views/users/_sidebar.html.haml
.default-container
  .l-side.clearfix
    %nav.mypage-nav
      %ul.mypage-nav-list
        %li
          =link_to users_path, class: "mypage-nav__list--item" do
            マイページ
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            お知らせ
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            やることリスト
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            いいね！一覧
            %i.fas.fa-angle-right.fa-lg
        %li
          = link_to new_item_path,class: "mypage-nav__list--item" do
            出品する
            %i.fas.fa-angle-right.fa-lg
        %li
          = link_to users_listing_path,class: "mypage-nav__list--item" do
            出品した商品 - 出品中
            %i.fas.fa-angle-right.fa-lg
        %li
          = link_to users_in_progress_path,class: "mypage-nav__list--item" do
            出品した商品 - 取引中
            %i.fas.fa-angle-right.fa-lg
        %li
          = link_to users_completed_path,class: "mypage-nav__list--item" do
            出品した商品 - 売却済み
            %i.fas.fa-angle-right.fa-lg
        %li
          = link_to users_purchase_path,class: "mypage-nav__list--item" do
            購入した商品 - 取引中
            %i.fas.fa-angle-right.fa-lg
        %li
          = link_to users_purchased_path,class: "mypage-nav__list--item" do
            購入した商品 - 過去の取引
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            ニュース一覧
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            評価一覧
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            ガイド
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            お問い合わせ
            %i.fas.fa-angle-right.fa-lg
      %h3.mypage-nav__head 売上・ポイント
      %ul.mypage-nav__list
        %li
          %a.mypage-nav__list--item
            売上・振込申請
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            ポイント
            %i.fas.fa-angle-right.fa-lg
      %h3.mypage-nav__head 設定
      %ul.mypage-nav__list
        %li
          = link_to edit_user_path(current_user.id), class: "mypage-nav__list--item" do
            プロフィール
            %i.fas.fa-angle-right.fa-lg
        %li
          = link_to edit_user_user_detail_path(:id, user_id: current_user.id), class: "mypage-nav__list--item" do
            住所変更
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            支払い方法
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            メール/パスワード
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            本人情報
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item
            電話番号の確認
            %i.fas.fa-angle-right.fa-lg
        %li
          = link_to "/users/logout/",class: "mypage-nav__list--item" do
            ログアウト
            %i.fas.fa-angle-right.fa-lg

app/views/users/completed.html.haml
= render partial: 'items/shared/header'
.mypage-container.clearfix
  %main.l-container
    %section.mypage-tab-container
      %h2.mypage-tab-head.bold 出品した商品
      %ul.listing-tabs
        %li
          =link_to users_listing_path do
            %h3.bold 出品中
        %li
          =link_to users_in_progress_path do
            %h3.bold 取引中
        %li.active
          =link_to users_completed_path do
            %h3.bold  売却済
      .tab-content
        - if @items.length != 0
          %ul.border.notification__content
            - @items.each do |item|
              %li
                .mypage-item-link
                  = link_to transaction_detail_path(item.id) do
                    - if item.images.present?
                      %figure
                        = image_tag item.images.first.image, width: "48", height: "48", class: "clearfix"
                    .mypage-item-body
                      .mypage-item-text
                        = item.item_name
                      .mypage-item-box.font-2
                        %i{class: "far fa-heart heart-icon"}
                        %span 10
                        .btn-blue.sell-btn 売却済み
                        %i.fas.fa-angle-right.fa-lg
        - else
          %ul.mypage-item-list
          %li.mypage-item-not-found.bold 売却済の商品がありません
    %ul.mypage-history
      %li.paper-prev.paper-cell
      %li.paper-nextpaper-cell
  = render partial: 'sidebar'
  = render partial: 'footer_sell_btn'
= render partial: 'items/shared/footer'

app/views/users/edit.html.haml
= render partial: 'items/shared/header'
.mypage-container.clearfix
  %main.l-container
    %section.title
      %h2
        プロフィール
    %section.profile-icon
      = form_for @user  do |f|
        %figure
          = image_tag 'member_photo_noimage_thumb.png', :size =>'60x60', class: "user-image"
        .name-form
          = f.text_field :nickname, class: "name-default", autofocus: true,placeholder: "Ann", value: @user.nickname
        .form
          = f.fields_for :user_detail do |d|
            = d.text_area :profile, class: "input-default",placeholder: "初めまして、よろしくお願いします。", value: @user.user_detail.profile
            = d.submit "変更する", class: "update-submit"
  = render partial: 'sidebar', locals: { user: @user }
  = render partial: 'footer_sell_btn'
= render partial: 'items/shared/footer'

app/views/users/in_progress.html.haml
= render partial: 'items/shared/header'
.mypage-container.clearfix
  %main.l-container
    %section.mypage-tab-container
      %h2.mypage-tab-head.bold 出品した商品
      %ul.listing-tabs
        %li
          =link_to users_listing_path do
            %h3.bold 出品中
        %li.active
          =link_to users_in_progress_path do
            %h3.bold 取引中
        %li
          =link_to users_completed_path do
            %h3.bold  売却済
      .tab-content
        - if @items.length != 0
          %ul.border.notification__content
            - @items.each do |item|
              %li
                .mypage-item-link
                  = link_to transaction_detail_path(item.id) do
                    - if item.images.present?
                      %figure
                        = image_tag item.images.first.image, width: "48", height: "48", class: "clearfix"
                    .mypage-item-body
                      .mypage-item-text
                        = item.item_name
                      .mypage-item-box.font-2
                        %i{class: "far fa-heart heart-icon"}
                        %span 10
                        - if item.status == "shipped"
                          .btn-blue.sell-btn 発送済み
                        - else
                          .btn-blue.sell-btn 配送待ち
                        %i.fas.fa-angle-right.fa-lg
        - else
          %ul.mypage-item-list
          %li.mypage-item-not-found.bold 取引中の商品がありません
    %ul.mypage-history
      %li.paper-prev.paper-cell
      %li.paper-nextpaper-cell
  = render partial: 'sidebar'
  = render partial: 'footer_sell_btn'
= render partial: 'items/shared/footer'

app/views/users/index.html.haml
= render partial: 'items/shared/header'
.mypage-container.clearfix
  %main.l-container
    .user-notification
      %section.user-icon
        %a
          %figure
            %img{alt: "顔写真1", src: "//static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png", width: "60"}/
          %h2.bold
          = current_user.nickname
          .user-number
            %div
              評価
              %span.bold 10
            %div
              出品数
              %span.bold
              = @item.length
      %section.notification-todo
        %ul.notification-todo__tabs
          %li.tab-notification.active
            %h3
              %a
                お知らせ
          %li.tab-notification
            %h3
              %a
                やることリスト
        %ul.notification__content
          %li
            %a.notification-todo__content-link
              %figure
                %img.clearfix{src: "//static-mercari-jp.akamaized.net/images/mercari_profile.png", width: "48"}/
              .notification-todo__content-body
                .notification-todo__content-link--text
                  発送のお知らせ
                %time
                  %i.far.fa-clock.my-gray
                  %span.my-gray 2 日前
                  %i.fas.fa-angle-right.fa-lg
          %li
            %a.notification-todo__content-link
              %figure
                %img.clearfix{src: "//static-mercari-jp.akamaized.net/images/mercari_profile.png", width: "48"}/
              .notification-todo__content-body
                .notification-todo__content-link--text
                  注文のお知らせ
                %time
                  %i.far.fa-clock.my-gray
                  %span.my-gray 2 日前
                  %i.fas.fa-angle-right.fa-lg
          %li
            %a.notification-todo__content-link
              %figure
                %img.clearfix{src: "//static-mercari-jp.akamaized.net/images/mercari_profile.png", width: "48"}/
              .notification-todo__content-body
                .notification-todo__content-link--text
                  注文のお知らせ
                %time
                  %i.far.fa-clock.my-gray
                  %span.my-gray 2 日前
                  %i.fas.fa-angle-right.fa-lg
          %li
            %a.notification-todo__content-link
              %figure
                %img.clearfix{src: "//static-mercari-jp.akamaized.net/images/mercari_profile.png", width: "48"}
              .notification-todo__content-body
                .notification-todo__content-link--text
                  個別メッセージ
                %time
                  %i.far.fa-clock.my-gray
                  %span.my-gray 2 日前
                  %i.fas.fa-angle-right.fa-lg
          %li.mypage-go-list
            %a 一覧を見る
    = render partial: "buying_item", locals: {items: @items, bought_items: @bought_items}
  = render partial: 'sidebar'
  = render partial: 'footer_sell_btn'
= render partial: 'items/shared/footer'

app/views/users/listing.html.haml
= render partial: 'items/shared/header'
.mypage-container.clearfix
  %main.l-container
    %section.mypage-tab-container
      %h2.mypage-tab-head.bold 出品した商品
      %ul.listing-tabs
        %li.active
          =link_to users_listing_path do
            %h3.bold 出品中
        %li
          =link_to users_in_progress_path do
            %h3.bold 取引中
        %li
          =link_to users_completed_path do
            %h3.bold  売却済
      .tab-content
        - if @items.length != 0
          %ul.border.notification__content
            - @items.each do |item|
              %li
                .mypage-item-link
                  = link_to transaction_detail_path(item.id) do
                    - if item.images.present?
                      %figure
                        = image_tag item.images.first.image, width: "48", height: "48", class: "clearfix"
                    .mypage-item-body
                      .mypage-item-text
                        = item.item_name
                      .mypage-item-box.font-2
                        %i{class: "far fa-heart heart-icon"}
                        %span 10
                        - if item.status == "stopped"
                          .btn-red.sell-btn 公開停止中
                        - else
                          .btn-blue.sell-btn 出品中
                        %i.fas.fa-angle-right.fa-lg
        - else
          %ul.mypage-item-list
          %li.mypage-item-not-found.bold 出品中の商品がありません
    %ul.mypage-history
      %li.paper-prev.paper-cell
      %li.paper-nextpaper-cell
  = render partial: 'sidebar'
  = render partial: 'footer_sell_btn'
= render partial: 'items/shared/footer'

app/views/users/purchase.html.haml
= render partial: 'items/shared/header'
.mypage-container.clearfix
  %main.l-container
    %section.mypage-tab-container
      %h2.mypage-tab-head.bold 購入した商品
      %ul.listing-tabs
        %li.half-tab.active
          =link_to users_purchase_path do
            %h3.bold 取引中
        %li.half-tab
          =link_to users_purchased_path do
            %h3.bold  購入済
      .tab-content
        - if @items.length != 0
          %ul.border.notification__content
            - @items.each do |item|
              %li
                .mypage-item-link
                  = link_to transaction_detail_path(item.id) do
                    - if item.images.present?
                      %figure
                        = image_tag item.images.first.image, width: "48", height: "48", class: "clearfix"
                    .mypage-item-body
                      .mypage-item-text
                        = item.item_name
                      .mypage-item-box.font-2
                        %i{class: "far fa-heart heart-icon"}
                        %span 10
                        - if item.status == "shipped"
                          .btn-blue.sell-btn 発送済み
                        - else
                          .btn-blue.sell-btn 配送待ち
                        %i.fas.fa-angle-right.fa-lg
        - else
          %ul.mypage-item-list
          %li.mypage-item-not-found.bold 取引中の商品がありません
    %ul.mypage-history
      %li.paper-prev.paper-cell
      %li.paper-nextpaper-cell
  = render partial: 'sidebar'
  = render partial: 'footer_sell_btn'
= render partial: 'items/shared/footer'

app/views/users/purchased.html.haml
= render partial: 'items/shared/header'
.mypage-container.clearfix
  %main.l-container
    %section.mypage-tab-container
      %h2.mypage-tab-head.bold 購入した商品
      %ul.listing-tabs
        %li.half-tab
          =link_to users_purchase_path do
            %h3.bold 取引中
        %li.half-tab.active
          =link_to users_purchased_path do
            %h3.bold  購入済
      .tab-content
        - if @items.length != 0
          %ul.border.notification__content
            - @items.each do |item|
              %li
                .mypage-item-link
                  = link_to transaction_detail_path(item.id) do
                    - if item.images.present?
                      %figure
                        = image_tag item.images.first.image, width: "48", height: "48", class: "clearfix"
                    .mypage-item-body
                      .mypage-item-text
                        = item.item_name
                      .mypage-item-box.font-2
                        %i{class: "far fa-heart heart-icon"}
                        %span 10
                        .btn-blue.sell-btn 購入完了
                        %i.fas.fa-angle-right.fa-lg
        - else
          %ul.mypage-item-list
          %li.mypage-item-not-found.bold 購入済の商品がありません
    %ul.mypage-history
      %li.paper-prev.paper-cell
      %li.paper-nextpaper-cell
  = render partial: 'sidebar'
  = render partial: 'footer_sell_btn'
= render partial: 'items/shared/footer'

app/views/users/show.html.haml
= render partial: 'items/shared/header'
.mypage-container.clearfix
  %main.p-container
    %section.user-icon
      %a
        %figure
          %img{alt: "顔写真1", src: "//static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png", width: "60"}/
        %h2.bold
          = @user.nickname
        .user-number
          %div
            評価
            %span.bold 0
          %div
            出品数
            %span.bold 0
    .profile_form
      .profile_field
        -if @userdetail.nil?
          プロフィール情報はありません。
        -else
          = simple_format(@user.user_detail.profile)
= render partial: 'items/shared/footer'