config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
  }

  devise_scope :user do
    get  'users/index' => 'users/registrations#index'
    post 'sign_up' => 'users/registrations#new'
    post 'users/logout'  => 'users/sessions#logout'
  end

  root 'items#index'
  get "users/in_progress" => "users#in_progress"
  get "users/completed" => "users#completed"
  get "users/purchase" => "users#purchase"
  get "users/purchased" => "users#purchased"
  get "users/listing" => "users#listing"
  get "users/logout" => "users#logout"
  resources :users, only: [:index, :edit, :update, :show] do
      resources :user_details, only: [:new , :create, :edit, :update]
  end
  get "items/area/:prefecture" => "items#area"
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    post :payjp, on: :member
    get :buy, on: :member
    get :stop, on: :member
    get :resume, on: :member
  end
  post "items/create" => "items/create"
  resources :category, only: [:index,:show]

  resources :blands, only: [:index]

  resources :large_category, only: [:show, :index] do
    resources :medium_category, only: [:show] do
      resources :small_category, only: [:show]
    end
  end

  # get "large_category/:large_category_id" => "category#large_category"
  # get "category/medium_category/:large_category_id/:medium_category_id" => "category#medium_category"
  # get "category/small_category/:large_category_id/:medium_category_id/:small_category_id" => "category#small_category"

  resources :transaction_details, only: [:show, :update]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :saler, class_name:"User", optional: true
  belongs_to :buyer, class_name:"User", optional: true
  belongs_to :large_category
  belongs_to :medium_category
  belongs_to :small_category
  belongs_to :bland, optional: true
  has_many :images, dependent: :delete_all
  accepts_nested_attributes_for :images
  validates :item_name, presence: true,length: { maximum: 40 }
  validates :description, length: { maximum: 1000 } ,presence: true
  validates :size, presence: true
  validates :condition, presence: true
  validates :charge_method, presence: true
  validates :prefecture, presence: true
  validates :handling_time, presence: true
  validates :price,presence: true
  validates :delivery_method, presence: true
  validates :price,numericality:{ greater_than: 299, less_than: 10000000}, presence: true
  enum prefecture: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7, 茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14, 新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20, 岐阜県:21,静岡県:22,愛知県:23,三重県:24, 滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30, 鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35, 徳島県:36,香川県:37,愛媛県:38,高知県:39, 福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  enum status: {displayed: 0, shipped: 1, received: 2 ,trading: 3, stopped: 4}
    scope :be_sold, -> { where.not(buyer_id: nil) }
    scope :be_bought, -> (user_id) { where("buyer_id = ?", user_id) }
    scope :be_indexed, ->{ where.not(status: :stopped).where.not(status: :received) }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  PICTURE_COUNT = 4
  before_action :set_item ,only:[:payjp,:destroy,:show,:edit,:update,:stop,:resume,:buy]
  def payjp
    require 'payjp'
    Payjp.api_key = PAYJP_SECRET_KEY
    @user = User.find(current_user.id)
    @item.with_lock do
      if @item.buyer_id == nil && @item.status == "displayed"
        Payjp::Charge.create(
          :amount => @item.price,
          :card => params['payjp-token'],
          :currency => 'jpy',
        )
        @item.update!(buyer_id: @user.id)
        @item.update!(status: :trading)
        redirect_to  users_purchase_path
        flash[:notice] = '購入が完了しました。'
      else
        redirect_to :root
        flash[:alert] = '購入に失敗しました。申し訳ありません。入力中に出品停止されたか、他ユーザーに売却されました。'
      end
    end
  end

  def index
    @items = Item.be_indexed.order("RAND()").limit(4)
    @ladies_items = Item.where(large_category_id: '1').be_indexed.order("created_at DESC").limit(4)
  end

  def new
    if user_signed_in?
      @item = Item.new
      @item.images.build
    else
      redirect_to new_current_user_session_path
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to users_listing_path
      flash[:notice] = "出品を完了しました。"
    else
      flash[:alert] = "出品に失敗しました。"
      redirect_to :root
    end
  end

  def destroy
    if @item.user_id == current_user.id
       @item.destroy
       redirect_to users_listing_path
       flash[:notice] = "削除を完了しました。"
    else
       redirect_to item_path(@item)
       flash[:notice] = "削除に失敗しました。"
    end
  end

  def show
    @images = @item.images.order("created_at DESC")
    @other_items = Item.where(user_id: @item.user_id).be_indexed.where.not(id: @item.id).limit(3)
  end

  def edit
    @item = Item.find(params[:id])
    if @item.user_id != current_user.id
      redirect_to root_path, notice: "権限がありません"
    end
    @item.image = Image.new if @item.images.blank?
    count = @item.images.count
    (PICTURE_COUNT - count).times {@item.images.build}
  end

  def update
    if @item.update(item_params)
      redirect_to users_listing_path
      flash[:notice] = "編集を完了しました。"
    else
      redirect_to edit_item_path
      flash[:alert] = "編集に失敗しました。"
    end
  end

  def stop
    if @item.update(status: :stopped)

      redirect_back(fallback_location: root_path)
      flash[:notice] = "出品の一旦停止をしました。"
    else
      redirect_to item_path(@item)
      flash[:alert] = "出品の一旦停止に失敗しました。"
    end
  end

  def resume
    if @item.update(status: :displayed)

      redirect_back(fallback_location: root_path)
      flash[:notice] = "出品の再開をしました。"
    else
      redirect_to item_path(@item)
      flash[:alert] = "出品の再開に失敗しました。"
    end
  end

  def buy
    if user_signed_in? && current_user.user_detail == nil
      @user_detail = current_user.user_detail
      redirect_to new_user_user_detail_path(user_id: current_user.id)
      flash[:warning] = "住所入力をしてください"
    elsif  user_signed_in?
      @user_detail = current_user.user_detail
      @image = @item.images.first
    else
      redirect_to new_current_user_session_path
    end
  end

  def area
    @items = Item.where(prefecture: params[:prefecture])
  end


  private

  def item_params
    params.require(:item).permit(:item_name, :description, :size, :condition, :charge_method, :prefecture, :handling_time, :price, :large_category_id, :medium_category_id, :small_category_id, :bland_id, :delivery_method,images_attributes:[:image, :image_cache, :_destroy, :id]).merge(status: :displayed).merge(user_id: current_user.id)
    # params.require(:item).permit(:item_name, :description, :size, :condition, :charge_method, :prefecture, :handling_time, :price, :large_category_id, :medium_category_id, :small_category_id, :bland_id, :delivery_method,images_attributes:[:image, :image_cache, :_destroy, :id]).merge(status: :displayed) #idは仮置きです。
  end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  / .sell-inner
  /   %h2.l-single-head  商品の情報を入力
  /   %form.sell-form
  /     .sell-upload-box
  /       %h3
  /         出品画像
  /         %span.form-require  必須
  /       %p  最大4枚までアップロードできます
  /       -# =render partial: "sell_img", locals: {image: @image}
  /       .sell-dropbox.clearfix
  /         .upload-dropbox
  /           .upload-dropbox__text
  /             ドラッグアンドドロップ
  /             %br またはクリックしてファイルをアップロード
  /             = f.fields_for :images do |i|
  /               = image_tag i.object.image, size: "75x75" if i.object.image.present?
  /               -# = i.file_field :image
  /               -# = i.hidden_field :id, value: i.object.id
  /             -# = f.fields_for :images do |i|
  /             -#   = i.label :image, "出品画像" do
  /             -#     = i.file_field :image
  .sell-content
    .form-group
      %label
        = f.label :item_name, "商品名" do
          商品名
          %span.form-require  必須
      = f.text_field :item_name, class: "input-default item-name", placeholder: "商品名（必須 40文字まで)"
    .form-group
      = f.label :description, "商品の説明" do
        商品の説明
        %span.form-require  必須
      =f.text_area :description,rows: 5, class: "input-default item-detail", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。"
  .sell-content.clearfix
    %h3.sell-sub-head  商品の詳細
    .sell-form-box
      .form-group
        %label
          = f.label :large_category_id, "カテゴリー" do
            カテゴリー
            %span.form-require  必須
        .select-wrap
          = f.collection_select :large_category_id,LargeCategory.all, :id, :large_category, {prompt: '---'}, class: "select-default"
          = fa_icon 'angle-down', class: 'angle-down-icon'
        .select-wrap
          = f.collection_select :medium_category_id,MediumCategory.all, :id, :medium_category, {prompt: '---'}, class: "select-default"
          = fa_icon 'angle-down', class: 'angle-down-icon'
        .select-wrap
          = f.collection_select :small_category_id,SmallCategory.all, :id, :small_category, {prompt: '---'}, class: "select-default"
          = fa_icon 'angle-down', class: 'angle-down-icon'
      .form-group
        = f.label :size, "サイズ" do
          サイズ
          %span.form-require  必須
        .select-wrap
          = f.select :size,[["XS以下","XS以下"],["S","S"],["M","M"],["L","L"],["XL","XL"],["XL以上","XL以上"], ["FREE SIZE","FREE SIZE"]], {prompt: '---'}, class: "select-default"
          = fa_icon 'angle-down', class: 'angle-down-icon'
      .form-group
        = f.fields_for :bland do |b|
          = b.label :bland, "ブランド"
          .select-wrap
            = b.text_field :bland, class: "select-default"
            = fa_icon 'angle-down', class: 'angle-down-icon'
      .form-group
        = f.label :condition, "商品の状態" do
          商品の状態
          %span.form-require  必須
        .select-wrap
          = f.select :condition,[["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], {prompt: '---'}, class: "select-default"
          = fa_icon 'angle-down', class: 'angle-down-icon'

  .sell-content.clearfix
    %h3.sell-sub-head  配送について
    %a.form-question
      = fa_icon 'question-circle', class: 'question-icon'
      .sell-form-box
        .form-group
          = f.label :charge_method,"配送料の負担" do
            配送料の負担
            %span.form-require  必須
          .select-wrap
            = f.select :charge_method,[["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)","着払い(購入者負担)"]],{prompt: '---'}, class: "select-default"
            = fa_icon 'angle-down', class: 'angle-down-icon'
        .form-group
          = f.label :delivery_method, "配送の方法" do
            配送の方法
            %span.form-require  必須
          .select-wrap
            = f.select :delivery_method,[["未定","未定"],["らくらくメルカリ便","らくらくメルカリ便"],["ゆうメール","ゆうメール"],["レターパック","レターパック"],["普通郵便（定形、定形外）","普通郵便（定形、定形外）"],["クロネコヤマト","クロネコヤマト"],["ゆうパック","ゆうパック"],["クリックポスト","クリックポスト"],["ゆうパケット","ゆうパケット"]],{prompt: '---'}, class: "select-default"
            = fa_icon 'angle-down', class: 'angle-down-icon'
        .form-group
          = f.label :prefecture,"発送元の地域" do
            発送元の地域
            %span.form-require  必須
          .select-wrap
            = f.select :prefecture,Item.prefectures.keys.to_a,{prompt: '---'}, class: "select-default"
            = fa_icon 'angle-down', class: 'angle-down-icon'
        .form-group
          = f.label :handling_time,"発送までの日数" do
            発送までの日数
            %span.form-require  必須
          .select-wrap
            = f.select :handling_time,[["1~2日で発送","1~2日で発送"],["2~3日で発送","2~3日で発送"],["4~7日で発送","4~7日で発送"]],{prompt: '---'}, class: "select-default"
            = fa_icon 'angle-down', class: 'angle-down-icon'
  .sell-content.clearfix
    %h3.sell-sub-head  販売価格(300〜9,999,999)
    %a.form-question
    = fa_icon 'question-circle', class: 'question-icon'
    .sell-form-box
      %ul.sell-price
        %li.form-group
          .clearfix
            = f.label :price,"価格", html:{class: "label l-left"} do
              価格
              %span.form-require  必須
            %label.l-right
              .price  ¥
              .price
                = f.text_field :price, class: "input-default", id: "amount", placeholder: "例）300"
        %li.clearfix
          .l-left  販売手数料 (10%)
          .l-right#commission  -
        %li.clearfix.bold
          .l-left  販売利益
          .l-right#sales-profit  -

app/views/items/_items.html.haml
%section.item-box
  =link_to item_path(item.id) do
    %figure.item-box__photo
      .item-box-image
        - if item.images.present?
          = image_tag item.images.first.image, size: "213x213"
          - if item.status == "trading" || item.status == "shipped"|| (item.status == "displayed" && item.buyer_id != nil)
            %figcaption
              .sold-badge-item.item-sold-out-badge.bold
                .sold-badge SOLD
        -else
          画像がありません。
    .item-box__text
      %h3.item-box__text__name.font-2
        = item.item_name
      .item-box__text__num.clearfix
        .item-box__text__num__price ￥
        .item-box__text__num__price
          = number_to_currency(item.price, unit: "",precision: 0)
        .item-box__text__num__likes.font-2
          %i{class: "far fa-heart heart-icon"}
          %span 10
        .item-box__text__num__tax  (税込)

app/views/items/_sell_img.html.haml
.sell-dropbox-container.clearfix
  .sell-upload-items
    %ul
      %li.sell-upload-item
        %figure.sell-upload-figure
          -# %img{src: "", class: "for-crop-class", id: "preview"}
          %input{type: "file", id: "getfile", multiple: true}
          #preview
        .sell-upload-button
          -# %a  編集
          -# %a  削除
      %li.sell-upload-item
      %li.sell-upload-item
      %li.sell-upload-item

app/views/items/area.html.haml
= render partial: 'items/shared/header'
%main.item-box-list.clearfix
  .item-content
    %section.item-box-content.clearfix
      %h1.items-box-head.clearfix.bold= "#{@items.first.prefecture}の商品一覧"
      = render partial: 'category/form', collection: @items, as: "item"
  = render partial: 'users/footer_sell_btn'
=render "items/shared/footer"

app/views/items/buy.html.haml
.single-container
  = render "items/shared/simple_header"
  %main.single-main
    %section.l-single-container.buy-item-container
      %h2 購入を確定しますか？
      %section.buy-item
        .buy-content
          .buy-content__image
            = image_tag @image.image, class: "buy-img"
          %p.buy-content__name.bold
          = @item.item_name
          .buy-content__form
            %span.buy-price.bold¥
            %span.buy-price.bold
              = number_to_currency(@item.price, unit:"", precision: 0)
              %span.item-shipping-fee 送料込み
            .buy-point
              ポイントを使う
              = fa_icon 'angle-down', class: "icon-arrow-right"
            .buy-price-table
              %ul.buy-you-pay.bold
                %li.buy-price-cell 支払い金額
                %li.buy-price-cell
                  %span.data-buy-pay￥
                  %span.data-buy-pay
                  = number_to_currency(@item.price, unit: "",precision: 0)
            - if (@user_detail.prefecture.present? && @user_detail.city.present? && @user_detail.address.present?)
              %p.has-error-text
                購入にお進みください。
              %button.btn-default.bold
                = form_tag action: :payjp, method: :post do
                  %script.payjp-button{"data-key" => PAYJP_PUBLIC_KEY, "data-text" => "購入する", src: "https://checkout.pay.jp/", type: "text/javascript"}
            - else
              %p.has-error-text 配送先の入力を完了してください。
              / 配送先と支払い方法の入力を完了してください。
              %button.btn-default.btn-gray.bold
                購入する
      %section.buy-item.buy-user-info
        .buy-content-inner
          %h3.bold 配送先
          %address.buy-user-info-text
            = "〒#{@user_detail.postal_code}"
            %br
              = @user_detail.prefecture
              = @user_detail.city
              = @user_detail.address
          .buy-user-info-fix
            = link_to "変更する", edit_user_user_detail_path(id: current_user.id, user_id: @user_detail.user_id)
            = fa_icon 'angle-right', class: "icon-arrow-right"
      %section.buy-user-info.buy-item
        .buy-content-inner
          %h3.bold 支払い方法
          %p.buy-user-info-text
            クレジット番号
          %a.buy-user-info-fix
            %span 変更する
            = fa_icon 'angle-right', class: "icon-arrow-right"
  = render "items/shared/simple_footer"
  :css
    #payjp_checkout_box input[type=button]
    {
    -webkit-appearance:none;
    border-radius:none;
    display:inline-block;
    padding:.5em 1em;
    font-size:12px;
    text-align:center;
    white-space:nowrap;
    vertical-align:middle;
    cursor:pointer;
    border:none;
    background-color: white;
    width: 320px;
    height: 50px;
    background-image: linear-gradient(#ea352d 0,#ea352d 48%,#ea352d 100%);

app/views/items/edit.html.haml
.single-container
  =render "items/shared/simple_header"
  %main.single-main
    %section.l-single-container
      = form_for @item do |f|
        .sell-inner
          %h2.l-single-head  商品の情報を入力
          %form.sell-form
            .sell-upload-box
              %h3
                出品画像
                %span.form-require  必須
              %p  最大4枚まで再アップロードできます
              .sell-dropbox
                .upload-dropbox
                  .upload-dropbox__text
                    = f.fields_for :images do |d|
                      = d.file_field :image, class: "input-default", value: @item.images
            .infomation-upload
              .item-form
                .item-form
                  .upload-box__text
                    = render partial: 'form', locals: {item: @item}
                    .sell-content.sell-btn-box
                      = f.submit "変更する", class: "btn-default btn-red"
                      = link_to 'もどる', :back, class: "btn-default btn-gray"
  =render "items/shared/simple_footer"

app/views/items/index.html.haml
.default-container
  -if user_signed_in?
    =render partial: "items/shared/header", locals: {}
  -else
    =render partial: "items/shared/header_signup"
  %main{class: "white", role: "main" }
    %section.top-main-visual
      .top-contents
        .top-main
          .main-title
            %h2  スマホでかんたん
            %h2  フリマアプリ
          .sub-title
            %p  メルカリはスマホカメラからすぐに出品できる
            %p  購入時も安心な独自システムのアプリです
          .top-main-visual-store.clearfix
            %a.pull-left
              %image{src: "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?2900942513", class: "app"}
            %a.pull-right
              %image{src: "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?2900942513",  class: "app"}
        %image{src: "//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?2900942513", class: "mobile"}
    .pickup-container
      %h2.pickup-head.bold  ピックアップカテゴリー
      %section.item-box-container.clearfix
        %h3.sub-title.bold
          .view-all-link
            ピックアップアイテム
        .items-box-content.clearfix
          =render partial: "items/items", collection: @items, as: "item"
        .view-all
          .view-all-link
            すべての商品を見る
      %section.item-box-container.clearfix
        %h3.sub-title.bold
          =link_to large_category_index_path(large_category_id: 1), class: "view-all-link" do
            レディース新着アイテム
        .items-box-content.clearfix
          =render partial: "items/items", collection: @ladies_items, as: "item"
        .view-all
          =link_to large_category_index_path(large_category_id: 1), class: "view-all-link" do
            すべての商品を見る
  = render partial: 'users/footer_sell_btn'
  =render "items/shared/footer"

app/views/items/prefecture.html.haml
= "#{@items.first.prefecture}の商品一覧"
- @items.each do |item|
  %section.item-box
    =link_to "/items/show/#{item.id}" do
      %figure.item-box__photo
        .item-box-image
          = image_tag item.images.first.image, :size => "213x213"
      .item-box__text
        %h3.item-box__text__name.font-2
          = item.item_name
        .item-box__text__num.clearfix
          .item-box__text__num__price
            = item.price
          .item-box__text__num__likes.font-2
            %i{class: "far fa-heart heart-icon"}
            %span 10
          .item-box__text__num__tax  (税込)

app/views/items/show.html.haml
-if user_signed_in?
  =render partial: "items/shared/header", locals: {}
-else
  =render partial: "items/shared/header_signup"
%section.item-box-container.l-single-container.item-single-contents
  %h1.item-detail-name.bold
    = @item.item_name
  .item-main-content.clearfix
    .item-photo
      .owl-carousel
        .owl-slider
          - if @item.images.present?
            = image_tag @item.images.first.image, size: "300x300"
            %figcaption
              - if @item.status == "shipped" || @item.status == "trading"
                .item-sold-out-badge.bold.sold-badge-item
                  .sold-badge SOLD
              - elsif @item.status == "stopped"
                .item-sold-out-badge.bold.stop-badge-item
                  .stop-badge 公開停止中
        .owl-dots
          .owl-dot
            - if @item.images.present?
              -@images.each do |image|
                = image_tag image.image, size: "75x75", class: "owl"
    %table.item-detail-table
      %tbody
        %tr
          %th 出品者
          %td
            =link_to user_path(@item.user.id) do
              = @item.user.nickname
            %ul
              %li.item-user-ratings
                %i{class: "far fa-kiss-wink-heart icon-good"}
                %span 105
              %li.item-user-ratings
                %i{class: "far fa-meh-blank icon-normal"}
                %span 10
              %li.item-user-ratings
                %i{class: "far fa-grin-tongue-squint icon-bad"}
                %span 1
        %tr
          %th カテゴリー
          %td
            =link_to large_category_path(large_category_id: @item.large_category_id) do
              = @item.large_category.large_category
            =link_to large_category_medium_category_path(large_category_id: @item.large_category_id , medium_category_id: @item.medium_category_id) do
              .item-detail-table-sub-category
                =fa_icon 'angle-right', class: "icon-arrow-right"
                = @item.medium_category.medium_category
            =link_to large_category_medium_category_small_category_path(large_category_id: @item.large_category_id,medium_category_id: @item.medium_category_id, small_category_id: @item.small_category_id) do
              .item-detail-table-sub-sub-category
                =fa_icon 'angle-right', class: "icon-arrow-right"
                = @item.small_category.small_category
        %tr
          %th ブランド
          - if @item.bland_id.present?
            %td
              =link_to blands_path(bland_id: @item.bland_id) do
                = @item.bland.bland
          - else
            %td
              未登録
        %tr
          %th 商品のサイズ
          %td
            = @item.size
        %tr
          %th 商品の状態
          %td
            = @item.condition
        %tr
          %th 配送料の負担
          %td
            = @item.charge_method
        %tr
          %th 配送の方法
          %td
            = @item.delivery_method
        %tr
          %th 配送元地域
          %td
            =link_to "/items/area/#{@item.prefecture}" do
              = @item.prefecture
        %tr
          %th 発送日の目安
          %td
            = @item.handling_time
  .item-price-box
    %span.item-price.bold ¥
    %span.item-price.bold
      = number_to_currency(@item.price, unit:"", precision: 0)
    %span.item.tax  (税込)
    %span.item-shipping-fee 送料込み
  - if user_signed_in? && current_user.id == @item.user_id && @item.buyer_id == nil &&(@item.status == "displayed" or @item.status =="stopped")
    .item-description
      %p
        = simple_format(@item.description)
    .item-change-box
    .btn__default
      = link_to "商品の編集",edit_item_path(@item),class: "btn__default--red"
      .btn__default--or
        or
      - if @item.status == "displayed"
        = link_to "出品を一旦停止する",stop_item_path(@item),class: "btn__default--grey"
      - else
        = link_to "出品を再開する",resume_item_path(@item),class: "btn__default--red"
      = link_to "この商品を削除する",item_path(@item),method: :delete, data: {confirm: "本当に削除しますか？"},class: "btn__default--grey"
  - elsif user_signed_in? && current_user.id == @item.user_id && (@item.status == "shipped" or @item.status =="trading" )
    .item-buy-text.btn-off.bold
      商品が購入されました。マイページから取引状況をご確認ください。
  - elsif user_signed_in? && @item.buyer_id == current_user.id  && (@item.status == "shipped" or @item.status =="trading" )
    .item-buy-text.btn-off.bold
      購入した商品です。マイページから取引状況をご確認ください。
  - elsif   @item.status == "shipped" or @item.status =="trading"
    .item-buy-btn.btn-off.bold
      売り切れました。
  - else
    = link_to '購入画面に進む', buy_item_path(@item), class: "item-buy-btn btn-red bold"
    .item-description
      %p
        = simple_format(@item.description)
      .item-button-container.clearfix
        .item-button-left
          %button.item-button.item-button-like
            %i{class: "far fa-heart heart-icon"}
            %span いいね！
            %span.fade-in-down 5
          %button.item-button.item-button-like.button-report.clearfix
            %i{class: "far fa-flag flag-icon"}
            %span 不適切な商品の報告
        .item-button-right
          %a
            = fa_icon 'lock', class: 'lock-icon'
            %span あんしん・あんぜんへの取り組み
.item-detail-message
  .message-container
    %form.message-form
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %textarea.textarea-default
      %button.message-submit.btn-default.btn-gray
        %span コメントする
%ul.nav-detail-item.clearfix
  %li.nav-item-link-prev
    %a
      = fa_icon 'angle-left', class: 'lock-icon'
      VANS スニーカー
  %li.nav-item-link-next
    %a
      ATSUGIフラワードット側ストッキング
      = fa_icon 'angle-right', class: 'lock-icon'
.item-social-media-box
  %ul.social-media-box
    %li
      %a
        %i{class: 'fab fa-facebook-square sns-icon facebook-icon'}
    %li
      %a
        %i{class: 'fab fa-twitter sns-icon twitter-icon'}
    %li
      %a
        %i{class: 'fab fa-line sns-icon line-icon'}
    %li
      %a
        %i{class: 'fab fa-pinterest-square sns-icon pinterest-icon'}
  .item-in-user-profile
    - if @other_items.length <= 0
      %h2.items-box-head.bold
        %a
          = "#{@item.user.nickname}さんのその他の商品はありません"
      .items-profile.items-box-content.clearfix
    - else
      %h2.items-box-head.bold
        %a
          = "#{@item.user.nickname}さんのその他の商品"
      .items-profile.items-box-content.clearfix
        = render partial: "items/shared/item_three" , collection: @other_items, as:"item"
= render partial: 'items/shared/footer'