config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
  }

  devise_scope :user do
    get  'users/index' => 'users/registrations#index'
    post 'sign_up' => 'users/registrations#new'
    post 'users/logout'  => 'users/sessions#logout'
  end

  root 'items#index'
  get "users/in_progress" => "users#in_progress"
  get "users/completed" => "users#completed"
  get "users/purchase" => "users#purchase"
  get "users/purchased" => "users#purchased"
  get "users/listing" => "users#listing"
  get "users/logout" => "users#logout"
  resources :users, only: [:index, :edit, :update, :show] do
      resources :user_details, only: [:new , :create, :edit, :update]
  end
  get "items/area/:prefecture" => "items#area"
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    post :payjp, on: :member
    get :buy, on: :member
    get :stop, on: :member
    get :resume, on: :member
  end
  post "items/create" => "items/create"
  resources :category, only: [:index,:show]

  resources :blands, only: [:index]

  resources :large_category, only: [:show, :index] do
    resources :medium_category, only: [:show] do
      resources :small_category, only: [:show]
    end
  end

  # get "large_category/:large_category_id" => "category#large_category"
  # get "category/medium_category/:large_category_id/:medium_category_id" => "category#medium_category"
  # get "category/small_category/:large_category_id/:medium_category_id/:small_category_id" => "category#small_category"

  resources :transaction_details, only: [:show, :update]
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user, optional: true, dependent: :destroy, foreign_key: "user_id"

  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :kana_family_name, presence: true
  validates :kana_first_name, presence: true
  validates :birthday, presence: true
  validates :prefecture, presence: true
  validates :city, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10}\z|\A\d{11}\z/ }
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :profile, length: { maximum: 5000 }

  enum prefecture:{
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7, 茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14, 新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20, 岐阜県:21,静岡県:22,愛知県:23,三重県:24, 滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30, 鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35, 徳島県:36,香川県:37,愛媛県:38,高知県:39, 福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController

  before_action :create_user_detail, only:[:edit]

  def new
    if user_signed_in?
      @userdetail = UserDetail.new
    else
      redirect_to new_user_user_detail_path
    end
  end

  def create
    @userdetail = UserDetail.new(user_detail_params)
    if @userdetail.save
      redirect_to root_path
    else
      redirect_to new_user_user_detail_path, alert: '住所登録に失敗しました'
    end
  end

  def edit
    if @userdetail.user_id != current_user.id
      redirect_to root_path, notice: "権限がありません"
    end
  end

  def update
    @user = User.find(current_user.id)
    @userdetail = @user.user_detail
    if @userdetail.update(user_detail_params)
      redirect_to root_path, notice: '変更が完了しました'
    else
      redirect_to edit_user_user_detail_path, alert: '住所編集に失敗しました'
    end
  end

private

  def user_detail_params
    params.require(:user_detail).permit(:family_name, :first_name, :kana_family_name, :kana_first_name, :birthday, :prefecture, :city, :address, :residential_name, :phone_number, :postal_code, :profile, :user_image).merge(user_id: current_user.id)
  end

  def create_user_detail
    @user = User.find(current_user.id)
    @userdetail = @user.user_detail
    if @userdetail.nil?
      redirect_to new_user_user_detail_path(current_user.id)
    end
  end
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/user_details/create.html.haml
.single-conteiner
  =render "items/shared/simple_header"
  .single-main
    .l-single-container
      .l-single-head
        %h2 アカウント作成完了
      .l-single-inner
        .l-single-content
          %a.next-submit{href: "/users/listing"}
            ユーザーページに進む
  =render "items/shared/simple_footer"

app/views/user_details/edit.html.haml
= render partial: 'items/shared/header'
.mypage-container.clearfix
  %main.l-container
    .l-single-container
      .l-single-head
        %h2 住所変更
    .l-single-form-content
      .l-single-inner
        .l-single-content
          = form_for [@user, @userdetail], url: user_user_detail_path do |f|
            .form-group
              = f.label :お名前
              = f.label :必須, class: "required btn-red"
              = f.text_field :family_name, class: "input-default", autofocus: true, placeholder: "例）山田"
              = f.text_field :first_name, class: "input-default", placeholder: "例）彩"
            .form-group
              = f.label :お名前カナ
              = f.label :必須, class: "required btn-red"
              = f.text_field :kana_family_name, class: "input-default", placeholder: "例）ヤマダ"
              = f.text_field :kana_first_name, class: "input-default", placeholder: "例）アヤ"
            .form-group
              = f.label :郵便番号
              = f.label :必須, class: "required btn-red"
              = f.text_field :postal_code, class: "input-default", placeholder: "例）1234567"
            .form-group
              = f.label :都道府県
              = f.label :必須, class: "required btn-red"
              = f.select :prefecture, UserDetail.prefectures.keys,{prompt: '選択してください'}, class: 'input-default'
            .form-group
              = f.label :市区町村
              = f.label :必須, class: "required btn-red"
              = f.text_field :city, class: "input-default", placeholder: "例）横浜市緑区"
            .form-group
              = f.label :番地
              = f.label :必須, class: "required btn-red"
              = f.text_field :address, class: "input-default", placeholder: "青山 1-1-1"
            .form-group
              = f.label :建物名
              = f.label :任意, class: "any btn-gray"
              = f.text_field :residential_name, class: "input-default", placeholder: "例）柳ビル103"
            .form-group
              = f.label :誕生日
              = f.label :必須, class: "required btn-red"
              = f.text_field :birthday, class: "input-default", placeholder: "例）1990年1月23日→19900123"
            .form-group
              = f.label :電話番号
              = f.label :必須, class: "required btn-red"
              = f.text_field :phone_number, class: "input-default", placeholder: "例）09012345678"

            .form-group
              = f.submit "変更する", class: "btn-default btn-red"
  = render partial: 'users/sidebar'
  = render partial: 'users/footer_sell_btn'
= render partial: 'items/shared/footer'

app/views/user_details/new.html.haml
.flash_wrapper
  .flash_box
    .flash_box--warning
      = flash.now[:warning]
.single-main
  =render "items/shared/simple_header"
  .l-single-container
    .l-single-head
      %h2 住所入力
    .l-single-inner
      .l-single-content
        = form_for [@user, @userdetail], url: user_user_details_path do |f|
          .form-group
            = f.label :お名前
            = f.label :必須, class: "required"
            = f.text_field :family_name, class: "input-default", autofocus: true, placeholder: "例）山田"
            = f.text_field :first_name, class: "input-default", placeholder: "例）彩"
          .form-group
            = f.label :お名前カナ
            = f.label :必須, class: "required"
            = f.text_field :kana_family_name, class: "input-default", placeholder: "例）ヤマダ"
            = f.text_field :kana_first_name, class: "input-default", placeholder: "例）アヤ"
          .form-group
            = f.label :郵便番号
            = f.label :必須, class: "required"
            = f.text_field :postal_code, class: "input-default", placeholder: "例）1234567"
          .form-group
            = f.label :都道府県
            = f.label :必須, class: "required"
            = f.select :prefecture, UserDetail.prefectures.keys,{prompt: '選択してください'}, class: 'input-default'
          .form-group
            = f.label :市区町村
            = f.label :必須, class: "required"
            = f.text_field :city, class: "input-default", placeholder: "例）横浜市緑区"
          .form-group
            = f.label :番地
            = f.label :必須, class: "required"
            = f.text_field :address, class: "input-default", placeholder: "青山 1-1-1"
          .form-group
            = f.label :建物名
            = f.label :任意, class: "any"
            = f.text_field :residential_name, class: "input-default", placeholder: "例）柳ビル103"
          .form-group
            = f.label :誕生日
            = f.label :必須, class: "required"
            = f.text_field :birthday, class: "input-default", placeholder: "例）1990年1月23日→19900123"
          .form-group
            = f.label :電話番号
            = f.label :必須, class: "required"
            = f.text_field :phone_number, class: "input-default", placeholder: "例）09012345678"
          .form-group
            = f.label :プロフィール
            = f.label :任意, class: "any"
            = f.text_area :profile, class: "input-default", placeholder: "5,000文字以内で自己紹介をお願いします"
          .form-group
            = f.submit "次へ進む", class: "next-submit"
  =render "items/shared/simple_footer"
  / = render "devise/shared/links"
  / = invisible_recaptcha_tags {"次へ進む", class: "next-submit"}
  / .form-group
  / = invisible_rechaptcha_tags , class: "next-submit"